/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swproject;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aya
 */
public class GenerateQuestion extends javax.swing.JFrame {

    /**
     * Creates new form GenerateQuestion
     */
    public GenerateQuestion() {
        initComponents();
        this.setBounds(150,25, 950, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Question :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 150, 100);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(209, 40, 650, 80);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jRadioButton1.setText("True");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(130, 280, 130, 39);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jRadioButton2.setText("False");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(130, 340, 120, 39);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Select Answer :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 180, 240, 110);

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 410, 130, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\NHG\\Documents\\NetBeansProjects\\PresentationCode\\SWProject\\schoolchoice(1).jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1090, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     //int NumberOfQuestion ;
     int countQuestions = 0 ;
     Game game ;
     
     
    void setGame(Game x )
    {
        game = x ;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        countQuestions++;
        String Question = jTextField1.getText();
        String Ans="";
        // should select true aw false maynf34 ysebo fady ... not handle in code
        if (jRadioButton1.isSelected())
        {
            Ans = "T";
        }
        else if (jRadioButton2.isSelected())
        {
            Ans = "F";
        }
        
        jTextField1.setText("");
        buttonGroup1.clearSelection();
     
        try {
            game.writeinfile(Question);
            game.writeinfile(Ans);
        } catch (IOException ex) {
            Logger.getLogger(GenerateQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (countQuestions == game.NumberOfQuestion)
        {
            JOptionPane.showMessageDialog(null, "Number of Questions is completed , " + game.GameName +" is Created ");
            this.hide();
        }    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
