/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swproject;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import static swproject.Questions.user;

/**
 *
 * @author Aya
 */
public class PlayGame extends javax.swing.JFrame {

    /**
     * Creates new form PlayGame
     */
    public PlayGame() {
       initComponents();
        this.setBounds(150,25, 950, 650);
    }
public   String GameName = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 240));
        setBounds(new java.awt.Rectangle(150, 25, 1100, 650));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(161, 60, 0, 0);

        jButton1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jButton1.setText("Choose Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 420, 380, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\NHG\\Documents\\NetBeansProjects\\PresentationCode\\SWProject\\schoolchoice (1).jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 980, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static StudentAccount user ;
    
    void set_user(StudentAccount sent )
    {
        user = sent;
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        JFileChooser F = new JFileChooser();
        int x = F.showOpenDialog(null);
   
        if (x==JFileChooser.APPROVE_OPTION)
        {
            File file = F.getSelectedFile();
            String FileName = file.getAbsolutePath();
            GameName = FileName ;
            
            //System.out.println("GAAAAAAAAAme = " + GameName);
        }
        
         try {
           
           
           this.hide();  
           Questions questions = new Questions(); 
           questions.show();
           questions.set_user(user);
           questions.Play(GameName);
           
           
           //questions.gamename = GameName;
            
            //System.out.println("Game NAme = " + GameName);
       
        } catch (IOException ex) {
            Logger.getLogger(PlayGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
//        Controller control = new Controller();
//        try {
//            control.ReconstructData();
//        } catch (IOException ex) {
//            Logger.getLogger(PlayGame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        Game game = new Game();
//        try {
//            game.PlayGame(game.Load(GameName));
//        } catch (IOException ex) {
//            Logger.getLogger(PlayGame.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
       // Questions questions = null;
       
       
        
       

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
